# Set the required OCP version
export ocp_version=4.13.19

# Set your cluster name and domain
export cluster_name=ocp1
export base_domain=example.com
# Set your ingress and api IP addresses (ignored for single node OpenShift (SNO)
export api_vip="10.0.1.216"
export ingress_vip="10.0.1.226"

# Be sure to set these two A records in DNS which match the above settings:
## api.<cluster_name>.<base_domain>     => api_vip
## *.apps.<cluster_name>.<base_domain>  => ingress_vip
# For SNO, be sure the DNS A records both point to the below 'starting_ip_index'

export machine_ip_prefix="10.0.1."
export prefix_length=24
export starting_ip_index=71
export mac_prefix="52:54:00:88:88:"

# Network 
export dns_server="10.0.1.8"
export next_hop_address="10.0.1.1"

# Prefix names for masters and workers
export master_prefix="master"
export worker_prefix="worker"

# Number of masters and workers. 
# Default is 3 masters & 2 (or more) workers.  
# Compact is 3 mastewrs and no workers 
# SNO is 1 master and zero workers 
export num_masters=3 
export num_workers=2

# Write your pull secret to this file. Download it from https://console.redhat.com/openshift/downloads#tool-pull-secret
#export pull_secret_file=pull-secret.json
export pull_secret_file=pull-secret-mirror.json
export additional_trust_bundle_file=~/quay-install/quay-rootCA/rootCA.pem
export ssh_key_file=~/.ssh/id_rsa.pub
export image_content_sources_file=image-content-sources.yaml


