apiVersion: v1alpha1
kind: AgentConfig
metadata:
  name: sno
rendezvousIP: 10.0.1.101
hosts:
  - hostname: master1
    role: master
    interfaces:
     - name: ens160
       macAddress: "52:54:22:88:88:01"
    networkConfig:
      interfaces:
        - name: ens160
          type: ethernet
          state: up
          mac-address: "52:54:22:88:88:01"
          ipv4:
            enabled: true
            address:
              - ip: 10.0.1.101
                prefix-length: 24
            dhcp: false
      dns-resolver:
        config:
          server:
            - 10.0.1.8
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 10.0.1.1
            next-hop-interface: ens160
  
